const user = require("../controllers/user");
const router = require("express").Router();
router.get("/", user.getUsers);
router.get("/:email", user.getUser);
router.get("/getUser/:id", user.getUserById);
router.get("/getUsers/sellers", user.getSellers);
router.put("/updateFollowers/:id", user.changeFollowersCount);
router.put("/updateFollowing/:id", user.changeFollowingCount);
router.put("/updateReviews/:id", user.increaseReviewCount);
router.put("/updateResponseTime/:id", user.changeResponseTime);
router.put("/updateRating/:id", user.changeStars);
router.put("/updateSearchHistory/:id", user.updateSearchHistory);
router.put("/makeSeller/:id", user.makeSeller);
router.put("/removeSeller/:id", user.removeSeller);
router.put("/updateProfile/:id", user.completeProfile);
router.put("/updateRecentSearches/:id", user.updateRecentSearches);
router.put("/updateBadge/:id", user.updateBadge);
router.put("/updateOnlineStatus/:id", user.updateOnlineStatus);
router.put("/updateCurrentBalance/:id", user.updateCurrentBalance);
router.put("/updateEarnings/:id", user.updateEarning);
router.put("/updateActiveOrders/:id", user.updateActiveOrders);
router.put("/updateCancelledOrders/:id", user.updateCancelledOrders);
router.put("/updateCompletedOrders/:id", user.updateCompletedOrders);
router.put("/updateSellerScore/:id", user.updateScore);
router.put("/banUser/:id", user.banUser);
router.put("/unBanUser/:id", user.unBanUser);

module.exports = router;
